-- Nova Era Venduss
-- Objetos deste sistema usam o prefixo nev_ para permanecerem isolados.

create schema if not exists nev_private;
revoke all on schema nev_private from public;

create table public.nev_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'agent' check (role in ('admin', 'agent')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table nev_private.nev_bootstrap_config (
  singleton boolean primary key default true check (singleton),
  token_hash text not null,
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Configure o acesso inicial diretamente no banco, por um canal privado.\n-- Não grave o hash do token de ativação em um repositório público.\n
create table public.nev_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  customer_name text not null check (char_length(btrim(customer_name)) between 2 and 120),
  whatsapp text not null check (whatsapp ~ '^[0-9]{10,15}$'),
  order_value numeric(12,2) not null default 0 check (order_value >= 0),
  issue_type text not null default 'other' check (
    issue_type in ('thai_order', 'missing_item', 'wrong_item', 'quality', 'refund', 'other')
  ),
  issue_description text not null check (char_length(btrim(issue_description)) between 3 and 4000),
  status text not null default 'open' check (
    status in ('open', 'in_progress', 'waiting_customer', 'resolved', 'cancelled')
  ),
  priority text not null default 'normal' check (
    priority in ('low', 'normal', 'high', 'urgent')
  ),
  assigned_to uuid references public.nev_profiles(user_id) on delete set null,
  created_by uuid not null default auth.uid() references public.nev_profiles(user_id) on delete restrict,
  resolution_type text check (
    resolution_type is null or resolution_type in ('store_credit', 'reorder', 'installment_refund', 'other')
  ),
  resolution_amount numeric(12,2) check (resolution_amount is null or resolution_amount >= 0),
  resolution_notes text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.nev_case_updates (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.nev_cases(id) on delete cascade,
  author_id uuid default auth.uid() references public.nev_profiles(user_id) on delete set null,
  kind text not null default 'note' check (kind in ('note', 'status', 'resolution', 'payment')),
  body text not null check (char_length(btrim(body)) between 1 and 4000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.nev_refund_plans (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null unique references public.nev_cases(id) on delete cascade,
  total_amount numeric(12,2) not null check (total_amount > 0),
  installment_count integer not null check (installment_count between 1 and 36),
  first_due_date date not null,
  status text not null default 'open' check (status in ('open', 'paid', 'cancelled')),
  created_by uuid not null default auth.uid() references public.nev_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.nev_refund_installments (
  id uuid primary key default gen_random_uuid(),
  refund_plan_id uuid not null references public.nev_refund_plans(id) on delete cascade,
  installment_number integer not null check (installment_number > 0),
  amount numeric(12,2) not null check (amount > 0),
  due_date date not null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'cancelled')),
  paid_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (refund_plan_id, installment_number)
);

create index nev_cases_status_idx on public.nev_cases(status);
create index nev_cases_created_at_idx on public.nev_cases(created_at desc);
create index nev_cases_assigned_to_idx on public.nev_cases(assigned_to);
create index nev_case_updates_case_id_idx on public.nev_case_updates(case_id, created_at desc);
create index nev_refund_installments_due_idx on public.nev_refund_installments(status, due_date);

create or replace function nev_private.nev_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger nev_profiles_set_updated_at
before update on public.nev_profiles
for each row execute function nev_private.nev_set_updated_at();

create trigger nev_cases_set_updated_at
before update on public.nev_cases
for each row execute function nev_private.nev_set_updated_at();

create trigger nev_refund_plans_set_updated_at
before update on public.nev_refund_plans
for each row execute function nev_private.nev_set_updated_at();

create trigger nev_refund_installments_set_updated_at
before update on public.nev_refund_installments
for each row execute function nev_private.nev_set_updated_at();

create or replace function nev_private.nev_is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.nev_profiles
    where user_id = auth.uid() and active = true
  );
$$;

create or replace function nev_private.nev_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.nev_profiles
    where user_id = auth.uid() and active = true and role = 'admin'
  );
$$;

create or replace function public.nev_claim_access(p_bootstrap_token text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_full_name text;
  v_has_profiles boolean;
  v_expected_hash text;
begin
  if v_user_id is null then
    raise exception 'É necessário entrar na conta.';
  end if;

  if exists (select 1 from public.nev_profiles where user_id = v_user_id) then
    return;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('nova-era-venduss-bootstrap', 0));

  if exists (select 1 from public.nev_profiles where user_id = v_user_id) then
    return;
  end if;

  select
    u.email,
    nullif(btrim(coalesce(u.raw_user_meta_data ->> 'full_name', '')), '')
  into v_email, v_full_name
  from auth.users u
  where u.id = v_user_id;

  if v_email is null then
    raise exception 'Não foi possível identificar o e-mail da conta.';
  end if;

  select exists (select 1 from public.nev_profiles) into v_has_profiles;

  if not v_has_profiles then
    select token_hash
    into v_expected_hash
    from nev_private.nev_bootstrap_config
    where singleton = true and used_at is null
    for update;

    if v_expected_hash is null
      or p_bootstrap_token is null
      or pg_catalog.encode(extensions.digest(p_bootstrap_token, 'sha256'), 'hex') <> v_expected_hash then
      raise exception 'Chave inicial inválida.';
    end if;

    insert into public.nev_profiles (user_id, email, full_name, role, active)
    values (v_user_id, lower(v_email), v_full_name, 'admin', true);

    update nev_private.nev_bootstrap_config
    set used_at = now(), used_by = v_user_id
    where singleton = true;
  else
    insert into public.nev_profiles (user_id, email, full_name, role, active)
    values (v_user_id, lower(v_email), v_full_name, 'agent', false);
  end if;
end;
$$;

create or replace function public.nev_admin_set_profile(
  p_user_id uuid,
  p_active boolean,
  p_role text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_role text;
  v_current_active boolean;
  v_admin_count integer;
begin
  if not nev_private.nev_is_admin() then
    raise exception 'Apenas administradores podem alterar a equipe.';
  end if;

  if p_role not in ('admin', 'agent') then
    raise exception 'Perfil inválido.';
  end if;

  select role, active
  into v_current_role, v_current_active
  from public.nev_profiles
  where user_id = p_user_id
  for update;

  if not found then
    raise exception 'Usuário não encontrado.';
  end if;

  if v_current_role = 'admin' and v_current_active = true
    and (p_role <> 'admin' or p_active = false) then
    select count(*) into v_admin_count
    from public.nev_profiles
    where role = 'admin' and active = true;

    if v_admin_count <= 1 then
      raise exception 'Mantenha ao menos um administrador ativo.';
    end if;
  end if;

  update public.nev_profiles
  set active = p_active, role = p_role
  where user_id = p_user_id;
end;
$$;

create or replace function public.nev_apply_resolution(
  p_case_id uuid,
  p_resolution_type text,
  p_amount numeric,
  p_notes text,
  p_installments integer default null,
  p_first_due_date date default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan_id uuid;
  v_total_cents bigint;
  v_base_cents bigint;
  v_remainder bigint;
  v_installment_cents bigint;
  v_index integer;
begin
  if not nev_private.nev_is_active_staff() then
    raise exception 'Acesso não autorizado.';
  end if;

  if p_resolution_type not in ('store_credit', 'reorder', 'installment_refund', 'other') then
    raise exception 'Tipo de solução inválido.';
  end if;

  if p_amount is null or p_amount < 0 then
    raise exception 'Informe um valor válido.';
  end if;

  if p_resolution_type = 'installment_refund' then
    if p_amount <= 0 then
      raise exception 'O reembolso precisa ter valor maior que zero.';
    end if;
    if p_installments is null or p_installments not between 1 and 36 then
      raise exception 'Informe de 1 a 36 parcelas.';
    end if;
    if p_first_due_date is null then
      raise exception 'Informe a data da primeira parcela.';
    end if;
  end if;

  update public.nev_cases
  set
    status = 'resolved',
    resolution_type = p_resolution_type,
    resolution_amount = round(p_amount, 2),
    resolution_notes = nullif(btrim(coalesce(p_notes, '')), ''),
    resolved_at = now()
  where id = p_case_id;

  if not found then
    raise exception 'Atendimento não encontrado.';
  end if;

  if p_resolution_type = 'installment_refund' then
    if exists (select 1 from public.nev_refund_plans where case_id = p_case_id) then
      raise exception 'Este atendimento já possui um plano de reembolso.';
    end if;

    insert into public.nev_refund_plans (
      case_id, total_amount, installment_count, first_due_date, created_by
    ) values (
      p_case_id, round(p_amount, 2), p_installments, p_first_due_date, auth.uid()
    ) returning id into v_plan_id;

    v_total_cents := round(p_amount * 100)::bigint;
    v_base_cents := v_total_cents / p_installments;
    v_remainder := v_total_cents % p_installments;

    for v_index in 1..p_installments loop
      v_installment_cents := v_base_cents + case when v_index <= v_remainder then 1 else 0 end;

      insert into public.nev_refund_installments (
        refund_plan_id, installment_number, amount, due_date
      ) values (
        v_plan_id,
        v_index,
        v_installment_cents::numeric / 100,
        (p_first_due_date + make_interval(months => v_index - 1))::date
      );
    end loop;
  end if;

  insert into public.nev_case_updates (case_id, author_id, kind, body, metadata)
  values (
    p_case_id,
    auth.uid(),
    'resolution',
    coalesce(nullif(btrim(coalesce(p_notes, '')), ''), 'Solução registrada.'),
    jsonb_build_object('resolution_type', p_resolution_type, 'amount', round(p_amount, 2))
  );
end;
$$;

create or replace function public.nev_mark_installment_paid(
  p_installment_id uuid,
  p_paid boolean,
  p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan_id uuid;
  v_case_id uuid;
  v_number integer;
  v_amount numeric;
begin
  if not nev_private.nev_is_active_staff() then
    raise exception 'Acesso não autorizado.';
  end if;

  select i.refund_plan_id, p.case_id, i.installment_number, i.amount
  into v_plan_id, v_case_id, v_number, v_amount
  from public.nev_refund_installments i
  join public.nev_refund_plans p on p.id = i.refund_plan_id
  where i.id = p_installment_id
  for update of i;

  if not found then
    raise exception 'Parcela não encontrada.';
  end if;

  update public.nev_refund_installments
  set
    status = case when p_paid then 'paid' else 'pending' end,
    paid_at = case when p_paid then now() else null end,
    notes = nullif(btrim(coalesce(p_notes, '')), '')
  where id = p_installment_id;

  update public.nev_refund_plans
  set status = case
    when exists (
      select 1 from public.nev_refund_installments
      where refund_plan_id = v_plan_id and status = 'pending'
    ) then 'open'
    else 'paid'
  end
  where id = v_plan_id;

  insert into public.nev_case_updates (case_id, author_id, kind, body, metadata)
  values (
    v_case_id,
    auth.uid(),
    'payment',
    case when p_paid
      then 'Parcela ' || v_number || ' marcada como paga.'
      else 'Pagamento da parcela ' || v_number || ' desmarcado.'
    end,
    jsonb_build_object('installment_number', v_number, 'amount', v_amount, 'paid', p_paid)
  );
end;
$$;

alter table public.nev_profiles enable row level security;
alter table public.nev_cases enable row level security;
alter table public.nev_case_updates enable row level security;
alter table public.nev_refund_plans enable row level security;
alter table public.nev_refund_installments enable row level security;

create policy nev_profiles_select
on public.nev_profiles for select
to authenticated
using (user_id = auth.uid() or nev_private.nev_is_active_staff());

create policy nev_cases_select
on public.nev_cases for select
to authenticated
using (nev_private.nev_is_active_staff());

create policy nev_cases_insert
on public.nev_cases for insert
to authenticated
with check (nev_private.nev_is_active_staff() and created_by = auth.uid());

create policy nev_cases_update
on public.nev_cases for update
to authenticated
using (nev_private.nev_is_active_staff())
with check (nev_private.nev_is_active_staff());

create policy nev_case_updates_select
on public.nev_case_updates for select
to authenticated
using (nev_private.nev_is_active_staff());

create policy nev_case_updates_insert
on public.nev_case_updates for insert
to authenticated
with check (nev_private.nev_is_active_staff() and author_id = auth.uid());

create policy nev_refund_plans_select
on public.nev_refund_plans for select
to authenticated
using (nev_private.nev_is_active_staff());

create policy nev_refund_installments_select
on public.nev_refund_installments for select
to authenticated
using (nev_private.nev_is_active_staff());

revoke all on public.nev_profiles from public, anon, authenticated;
revoke all on public.nev_cases from public, anon, authenticated;
revoke all on public.nev_case_updates from public, anon, authenticated;
revoke all on public.nev_refund_plans from public, anon, authenticated;
revoke all on public.nev_refund_installments from public, anon, authenticated;
revoke all on sequence public.nev_cases_case_number_seq from public, anon, authenticated;

grant select on public.nev_profiles to authenticated;
grant select, insert, update on public.nev_cases to authenticated;
grant select, insert on public.nev_case_updates to authenticated;
grant select on public.nev_refund_plans to authenticated;
grant select on public.nev_refund_installments to authenticated;
grant usage, select on sequence public.nev_cases_case_number_seq to authenticated;

revoke all on function nev_private.nev_is_active_staff() from public;
revoke all on function nev_private.nev_is_admin() from public;
grant usage on schema nev_private to authenticated;
grant execute on function nev_private.nev_is_active_staff() to authenticated;
grant execute on function nev_private.nev_is_admin() to authenticated;

revoke all on function public.nev_claim_access(text) from public;
revoke all on function public.nev_admin_set_profile(uuid, boolean, text) from public;
revoke all on function public.nev_apply_resolution(uuid, text, numeric, text, integer, date) from public;
revoke all on function public.nev_mark_installment_paid(uuid, boolean, text) from public;

grant execute on function public.nev_claim_access(text) to authenticated;
grant execute on function public.nev_admin_set_profile(uuid, boolean, text) to authenticated;
grant execute on function public.nev_apply_resolution(uuid, text, numeric, text, integer, date) to authenticated;
grant execute on function public.nev_mark_installment_paid(uuid, boolean, text) to authenticated;

comment on table public.nev_profiles is 'NEV: equipe autorizada do Nova Era Venduss';
comment on table public.nev_cases is 'NEV: atendimentos e pendências de clientes';
comment on table public.nev_case_updates is 'NEV: histórico de cada atendimento';
comment on table public.nev_refund_plans is 'NEV: acordos de reembolso parcelado';
comment on table public.nev_refund_installments is 'NEV: parcelas dos reembolsos';
